const works = [
  {
    id: '001',
    container: 'tonic-container',
    image: 'images/tonic-portfolio.png',
    name: 'Tonic',
    role: ['CANOPY', 'Back End Dev', 2015],
    description: 'A daily selection of privately personalized reads no accounts or sign-ups required.',
    content: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry`s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essent',
    technologies: ['images/html-tag.png', 'images/css-tag.png', 'images/javascript-tag.png'],
    liveLink: 'https://godiarksel.github.io/port-folio/',
    sourceLink: 'https://github.com/godiarksel/port-folio',
    alt: ['tonic', 'html-tag', 'css-tag', 'javascript-tag'],
  },
  {
    id: '002',
    container: 'tonic-container0',
    image: 'images/multi-post-portfolio.png',
    name: 'Multi-Post Stories',
    role: ['CANOPY', 'Back End Dev', 2015],
    description: 'A daily selection of privately personalized reads no accounts or sign-ups required.',
    content: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry`s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essent',
    technologies: ['images/html-tag.png', 'images/css-tag.png', 'images/javascript-tag.png'],
    liveLink: 'https://godiarksel.github.io/port-folio/',
    sourceLink: 'https://github.com/godiarksel/port-folio',
    alt: ['multi-post-portfolio', 'html-tag', 'css-tag', 'javascript-tag'],
  },
  {
    id: '003',
    container: 'tonic-container',
    image: 'images/tonic2.png',
    name: 'Tonic',
    role: ['CANOPY', 'Back End Dev', 2015],
    description: 'A daily selection of privately personalized reads no accounts or sign-ups required.',
    content: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry`s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essent',
    technologies: ['images/html-tag.png', 'images/css-tag.png', 'images/javascript-tag.png'],
    liveLink: 'https://godiarksel.github.io/port-folio/',
    sourceLink: 'https://github.com/godiarksel/port-folio',
    alt: ['tonic', 'html-tag', 'css-tag', 'javascript-tag'],
  },
  {
    id: '004',
    container: 'tonic-container0',
    image: 'images/multi-post-stories2.png',
    name: 'Multi-Post Stories',
    role: ['CANOPY', 'Back End Dev', 2015],
    description: 'A daily selection of privately personalized reads no accounts or sign-ups required.',
    content: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry`s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essent',
    technologies: ['images/html-tag.png', 'images/css-tag.png', 'images/javascript-tag.png'],
    liveLink: 'https://godiarksel.github.io/port-folio/',
    sourceLink: 'https://github.com/godiarksel/port-folio',
    alt: ['multi-post-stories2', 'html-tag', 'css-tag', 'javascript-tag'],
  },
];
export default works;